import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import Navbar from './navbar'
import renderPost from './render-post'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Forum Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <div className="flex-col centered-custom" align="center">
          <h1 className="mb-4">Welcome to our forum! <Link href="/posts">Check out some posts</Link> or <Link href="create-post">create your own</Link></h1>
        </div>
      </main>
    </>
  )
}
