import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import Navbar from './navbar'
import renderPost from './render-post'
import { useRouter } from 'next/router'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [postId, setPostId] = useState(null);
    const [content, setContent] = useState("");
    
    const router = useRouter();

    useEffect(() => {
        if (router.query && router.query.id === undefined) {
            setContent(
                <div>
                    <h1 className="mt-5">Error: No post specified</h1>
                    <Link href="/posts">Home</Link>
                </div>
            )
        } else {
            setPostId(router.query.id);
        }
    }, [router]);

  const callGetSetPosts = async () => {
    await fetch(`/api/get_posts?id=${postId}`, {
      method: 'GET',
      headers: {
          'Content-Type': 'application/json',
      }
    }).then(function (response) {
        if (response.ok) {
            return response.json();
        }
        throw response;
    }).then(function (data) {
        const { posts } = data;
        if (posts.length == 0) {
            setContent(
                <div>
                    <h1 className="mt-5">Error: Post not found</h1>
                    <Link href="/posts">Home</Link>
                </div>
            );
        } else {
            setContent(
                <div>
                    { posts.map((post) => renderPost(post)) }
                </div>
            );
        }
    }).catch(function (error) {
        console.warn("Error:",error)
        setContent(
            <div>
                <h1 className="mt-5">Error: Post not found</h1>
                <Link href="/posts">Home</Link>
            </div>
        );
    })
  }

  useEffect(() => {
    if (postId) {
        console.log("Post ID: ", postId)
        callGetSetPosts()
    }
  }, [postId]);

  return (
    <>
      <Head>
        <title>Forum Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <br/><br/>
        <div className="flex-col w-75" align="center">
            { content }
        </div>
      </main>
    </>
  )
}
